name: Deploy MkDocs para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache dependências
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Deploy para GitHub Pages
        run: mkdocs gh-deploy --force